Universe              = vanilla
executable            = invalidate_dbs_files_TTHto2B_2022_LLPmini.sh
arguments             = $(ProcId) 30
GetEnv                = True
+Remote_Schedd = "bird-htc-sched11.desy.de"
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
requirements 	        = (OpSysAndVer == "CentOS7" || OpSysAndVer == "RedHat9")
request_memory        = 2 GB
+JobFlavour           = "workday"

queue 6
